### PR TITLE
Updates per sprint 5 discussions

### PR DESCRIPTION
**Pull request by phirefly**
Updates to the Epic/Sprint planning excel doc per sprint 5 discussions

### CODE REVIEW

**Comment by mgwalker** [comment]
@phirefly Do you want someone else to look at this before we merge it?  If so, who should that be?  If not, I'll mark it as reviewed so we can merge.

**Comment by phirefly** [comment]
@mgwalker Yes, please merge. No review is necessary. Let me know if I should just be merging this myself in the future (or if there's a better way to communicate that it just needs to be merged in). It's basically documentation.

**Comment by phirefly** [comment]
Oh, looks like I can merge my own PRs anyway. :)

**Comment by mgwalker** [comment]
Yeah, we've set it up that merges to master require a review, just to make sure everything gets a second set of eyes.  For these kinds of things, feel free to add me as a reviewer and just let me know it's good to go and I'll mark it approved.  😄

**Pull request merged**
