### PR TITLE
Split apiService into multiple files

### PR DESCRIPTION
**Pull request by mgwalker**
# Just an idea

This PR doesn't need to be merged unless @davoodharun thinks it's worthwhile.  It's mostly just me looking at how to improve the CodeClimate score.  Ideally the tests would change as well (and could possibly be simplified), but since from the outside, nothing has changed, the current tests are also okay.

If this is a good direction to go, however, I'll tackle modifying the tests.

---

#### What's this PR do?

To help reduce the low [CodeClimate score on apiService.js](https://codeclimate.com/github/18F/dol-whd-14c/DOL.WHD.Section14c.Web/src/modules/services/apiService.js), this PR splits the apiService into multiple files using factory methods for dependency injection.  All tests still pass.

#### How should this be manually tested?

Pull the code, build, and run.  Make sure API calls from the web client still work.

#### Any background context you want to provide?

There are only two especially bad scores on CodeClimate, and one of them is `apiService.js`.  The main issues are method lines-of-code and cyclomatic complexity.  This PR breaks `apiService` into multiple files to reduce the lines of code of the various files and the `exports` method.

### CODE REVIEW

**Comment by davoodharun** [comment]
@mgwalker, sorry I didn't realize I had an action on this.. I think this is a good idea. Would it be possible to resolve the merge conflicts locally? Sorry, I think this PR fell a bit behind from sitting in the queue for so long.

**Comment by mgwalker** [comment]
@davoodharun Yep, I can do that.  It will probably be later today.  Want me to ping you here or on Slack when it's done?  Or alternatively, I can sit on it until the "pause" and then it'll be ready for you when we resume in January.

**Comment by mgwalker** [comment]
@davoodharun I was wrong, it did not take until afternoon.  😂

**Comment by davoodharun** [comment]
@mgwalker this doesn't need any subsequent changes to external files that were calling apiService previously, correct?

**Comment by mgwalker** [comment]
@davoodharun That should be correct.  The place where it's `require`d should still resolve correctly.  It builds on my machine and on CircleCI, so it's resolving, at least.  Beyond that, the tests for `apiService` should prove that the component pieces are pulled in correctly (or else the tests would fail because a bunch of stuff would be missing).

**Pull request closed without merging**
