### PR TITLE
make invitation email subject and body clearer

### PR DESCRIPTION
**Pull request by suprenant**
Make email invitation copy clearly identifiable as involving DOL 14(c) so users are reminded of why they are receiving this email.

(please adjust if you see room for improvement!)

### CODE REVIEW

**Comment by mgwalker** [comment]
@EStriegel What do you think?

Also @suprenant, should these be targeting `sprint/3` instead of `master`?  I already merged a couple of them before I realized they were going into `master`...  😬  I think it's *okay* either way, but putting them into `sprint/3` would reduce the risk of any conflicts at the end of the sprint.

**Comment by suprenant** [comment]
@mgwalker is it our standard to target the current sprint instead of `master`? If that's the case, I can do that. 

Thanks for your patience as I get up to speed with process here!

**Comment by mgwalker** [comment]
@suprenant Yes, that's it. 🙂

**Comment by suprenant** [comment]
@mgwalker I made the requested change – I think I did that right. Let me know if anything further is needed, thanks!

**Pull request merged**
