### PR TITLE
fix 146

### PR DESCRIPTION
**Pull request by brendansudol**
fixes https://github.com/18F/dol-whd-14c/issues/146

preview:
screen shot 2017-09-01 at 10 34 26 am

### CODE REVIEW

**Comment by mgwalker** [comment]
@EStriegel Can you confirm that #146 applies to both the "legal name of the employer" and "is the employer a state educational agency" questions?

**Comment by brendansudol** [comment]
Ah, I misread this issue as saying to remove all extra instructions from this page (in favor of the blue help section) -- I will update to reflect just the one extra instruction deletion

**Comment by EStriegel** [comment]
@mgwalker @brendansudol Yes, looking at it now and there are three questions in the Employer section that have instruction text outside of the blue instruction box - "Legal Name of Employer", "Does the Employer have a Parent Organization?", and "Is this employer a local or State educational agency?".  All of that text should be removed.  The text in the blue boxes should reflect what I uploaded in #177.  

Apologies for these edits being all over the place!

**Comment by brendansudol** [comment]
great, thanks @EStriegel 

@mgwalker -- i believe all of that extra text is gone

**Pull request merged**
