### PR TITLE
Minor text fixes

### LINKED ISSUE #145: Text Edit: Employer Section - Employer Status - instruction language correction, "check public" should be "select public".

### LINKED ISSUE #147: Text Edit: Employer Section - From SCA question - delete from instructions: "If the employer had one or more SCA-covered contracts during the last completed fiscal quarter, provide the total number of SCA contracts and attach the SCA Wage Determinations for each contract."

### LINKED ISSUE #148: Text Edit: Employer Section - From the deduction question, delete from instructions - "Provide a brief description of the type of deduction taken by the employer (e.g., transportation, rent, meals)."

### LINKED ISSUE #154: Text Edit: PW Add Source ER, *experienceD worker wage"

### PR DESCRIPTION
**Pull request by mgwalker**
* Changes "experience worker wage" to "experienced worker wage".  Closes #154.
* Removes some instruction text.  Closes #148.
* Removes some instruction text.  Closes #147.
* Fixes some UI-related text.  Closes #145.

### CODE REVIEW

**Comment by mmurthydol** [comment]
All: This story must remain in ZenHub and prioritized very high. A parallel story created on the DOL side. 

If the DOL side of the story is finished prior to vendor start date:
1) 18F repository needs to be updated with changes in DOL master repository (WHD, OCIO, 18F can talk through this). 
2) This story can be closed.

If not this story remains open and DOL story will be closed.

**Comment by oghaffari** [comment]
Individual text fixes referenced have their own user-stories in the Backlog. This is being closed as a result.

**Comment by mgwalker** [comment]
Reopening because this is a pull request that actually fixes those things, not a list of things that needs fixing.  😄

**Comment by phirefly** [comment]
I would suggest we deploy these changes to the dev environment and have @EStriegel validate there. @mmurthydol @binwang89 would that be a reasonable approach now that the dev environment is up and running?

**Comment by mmurthydol** [comment]
@phirefly  let's have a conversation internally regarding timing/feasibility.

**Pull request merged**
