### PR TITLE
add parentheses to 14(c) in header

### PR DESCRIPTION
**Pull request by suprenant**
Add parentheses for consistency (unless there's a technical or stylistic reason that these shouldn't be added)

### CODE REVIEW

**Comment by mgwalker** [comment]
@EStriegel I'm probably going to bug you for approval on each of these.  :)

**Comment by suprenant** [comment]
Thanks @mgwalker – I wasn't sure about process and will add Liz as a reviewer for next time :)

**Comment by EStriegel** [comment]
@mgwalker @suprenant Someone will have to walk me through how to be a reviewer.  :)

**Comment by suprenant** [comment]
@mgwalker are you up for giving Liz a tutorial (which I could join, pending schedules)? 

I can do it, but I'm still absorbing some of our working process and don't want to steer her wrong.

**Comment by mgwalker** [comment]
You bet

**Pull request merged**
